global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: 'rest-api'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /metrics