POST http://localhost:8080/events
Content-Type: application/json

{
    "Name": "Prometheus Sixth",
    "Description": "Sixth request to track",
    "Location": "Thee 6th request location",
    "DateTime": "2025-05-23T15:30:00.000Z"
}