POST http://localhost:8080/events
Content-Type: application/json

{
    "Name": "Round Two",
    "Description": "All play arcade",
    "Location": "An arcade location",
    "DateTime": "2024-11-18T15:30:00.000Z"
}